books/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import search_results
from .views import view_wishlist



app_name = 'books'

urlpatterns = [
    path('books/', views.book_list, name='book_list'),
    path('', views.home, name='home'),  
    path('<int:book_id>/', views.book_detail, name='book_detail'),
    path('login/', auth_views.LoginView.as_view(template_name='books/login.html'), name='login'),
    path('signup/', views.signup, name='signup'),  # Add signup view
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # Add logout view
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),  # Add password reset view
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('latest_reviews/', views.latest_reviews, name='latest_reviews'),
    path('top_rated/', views.top_rated, name='top_rated'),
    path('community/', views.community, name='community'),
    path('about/', views.about, name='about'),
    path('add/', views.add_book, name='add_book'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('search/', search_results, name='search_results'),
    path('submit_review/', views.submit_review, name='submit_review'),
    path('<str:genre_name>/', views.genre_books, name='genre_books'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.view_wishlist, name='view_wishlist'),


    
]
    

books/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Genre(models.Model):
    GENRE_CHOICES = [
        ('FICTION', 'Fiction'),
        ('NON-FICTION', 'Non-Fiction'),
        ('AUTOBIOGRAPHY', 'Autobiography'),
        ('NOVELS', 'Novels'),
        ('THRILLERS', 'Thrillers'),
        ('HISTORY', 'History'),
        ('POETRY', 'Poetry'),
    ]

    name = models.CharField(max_length=20, choices=GENRE_CHOICES)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    cover_image = models.ImageField(upload_to='covers/')
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)



    def __str__(self):
        return self.title

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.CharField(max_length=100)  # Assuming a simple user field for demonstration
    text = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    rating = models.PositiveIntegerField(default=0)  # Default value added here
    comment = models.TextField()
    comment = models.CharField(max_length=200, default='')

    def __str__(self):
        return f"Review for {self.book.title} by {self.user}"
    


class Wishlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='wishlist')
    books = models.ManyToManyField(Book)  # Assuming you have a Book model

    def __str__(self):
        return f"{self.user}'s Wishlist"
    
   



    

books/forms.py
from django import forms
from .models import Book,Genre

class BookAdminForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    GENRE_CHOICES = [
        ('FICTION', 'Fiction'),
        ('NON-FICTION', 'Non-Fiction'),
        ('AUTOBIOGRAPHY', 'Autobiography'),
        ('NOVELS', 'Novels'),
        ('THRILLERS', 'Thrillers'),
        ('HISTORY', 'History'),
        ('POETRY', 'Poetry'),
    ]

genre = forms.ModelChoiceField(
        queryset=Genre.objects.all(),
        required=True,
        widget=forms.Select(attrs={'class': 'select2'}),
    )

books/views.py
from django.shortcuts import render,get_object_or_404
from .models import Book
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from .models import Review
from .forms import BookAdminForm
from django.db.models import Q
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from .models import  Book,Genre,Wishlist
from django.db.models.functions import Lower
from django.views.decorators.http import require_POST
from django.http import JsonResponse
import logging






# Create your views here.
def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'books': books})

def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'books/book_detail.html', {'book': book})

def home(request):
    # Fetch the latest 5 books from the database
    latest_books = Book.objects.all().order_by('-id')[:34]  # assuming newer books have a higher ID
    return render(request, 'books/home.html', {'latest_books': latest_books})

def login_view(request):
    # Your login view logic here
    return render(request, 'books:home')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('books:home')
    else:
        form = UserCreationForm()
    return render(request, 'books/signup.html', {'form': form})

def logout_view(request):
    # Your logout view logic here
    return render(request, 'books/logout.html')

def password_reset_view(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            form.save(request=request)
            messages.success(request, 'An email has been sent with instructions to reset your password.')
            return redirect('books:password_reset_done')
    else:
        form = PasswordResetForm()
    return render(request, 'books/password_reset.html', {'form': form})

class CustomPasswordResetDoneView(PasswordResetDoneView):
    # Your custom password reset done view logic here
    template_name = 'books/password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    # Your custom password reset confirm view logic here
    template_name = 'books/password_reset_confirm.html'

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    # Your custom password reset complete view logic here
    template_name = 'books/password_reset_complete.html'


def latest_reviews(request):
    # Get the latest 10 reviews
    latest_reviews = Review.objects.all().order_by('-date_posted')[:10]
    return render(request, 'books/latest_reviews.html', {'reviews': latest_reviews})

def top_rated(request):
    # Get the top 10 rated books
    top_rated_books = Book.objects.all().order_by('-average_rating')[:10]
    return render(request, 'books/top_rated.html', {'books': top_rated_books})




def community(request):
    # Example: Retrieve the latest 10 reviews or user posts for the community page
    latest_community_posts = Review.objects.all().order_by('-date_posted')[:10]

    # Pass the posts to the template
    return render(request, 'books/community.html', {'community_posts': latest_community_posts})

def about(request):
    # You can pass additional context if needed, such as team member information, etc.
    context = {
        'page_title': 'About Us'  # You can use this in your template to set the page title
    }
    return render(request, 'books/about.html', context)

def add_book(request):
    if request.method == 'POST':
        form = BookAdminForm(request.POST, request.FILES)

        if form.is_valid():
            book = form.save(commit=False)
            genre_name = form.cleaned_data['genre']
            try:
                genre = Genre.objects.get(name=genre_name)
                book.genre = genre
                book.save()
                return redirect('books:book_list')
            except Genre.DoesNotExist:
                messages.error(request, 'Invalid genre selected.')
        else:
            messages.error(request, 'Invalid form data. Please check the form fields.')
    else:
        form = BookAdminForm()

    return render(request, 'books/add_book.html', {'form': form})



def search_results(request):
    search_query = request.GET.get('search_query', '').strip()
    print("Search Query:", search_query)  # Add this line for debugging
    if search_query:
        # Use 'icontains' for case-insensitive partial matches in title or author
        books = Book.objects.filter(
            Q(title__icontains=search_query) | Q(author__icontains=search_query)
        )
        print("Books Found:", books)  # Add this line for debugging
    else:
        books = []

    return render(request, 'books/search_results.html', {'books': books})


@login_required
def submit_review(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            rating = data.get('rating')
            comment = data.get('comment')

            # Save the review data to your database (e.g., using a Django model)
            new_review = Review.objects.create(
                user=request.user,  # Assuming you have a 'user' field in your Review model
                rating=rating,
                comment=comment
            )

            response_data = {
                'success': True,
                'message': 'Review submitted successfully!',
                'comment': comment,
            }

            # Print the newly created review for debugging purposes
            print(f"New Review - Rating: {rating}, Comment: {comment}")

            return JsonResponse(response_data)
        except Exception as e:
            response_data = {
                'success': False,
                'message': 'Error while submitting the review.',
            }
            return JsonResponse(response_data, status=400)
        
def genre_books(request, genre_name):
    try:
        # Adjust the query to be case-insensitive
        genre = Genre.objects.get(name__iexact=genre_name.upper())
        books = Book.objects.filter(genre=genre)
    except Genre.DoesNotExist:
        genre = None
        books = []

    context = {
        'genre': genre,
        'books': books,
    }
    return render(request, 'books/genre_books.html', context)



logger = logging.getLogger(__name__)

@csrf_exempt
@login_required
def add_to_wishlist(request):
    if request.method == 'POST':
        book_id = request.POST.get('bookId')
        try:
            book = Book.objects.get(id=book_id)
            request.user.wishlist.add(book)
            return JsonResponse({'success': True})
        except Book.DoesNotExist:
            return JsonResponse({'error': 'Book not found'}, status=404)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)


@login_required
def view_wishlist(request):
    print("Viewing wishlist")  # For debugging
    wishlist, created = Wishlist.objects.get_or_create(user=request.user)
    return render(request, 'books/wishlist.html', {'wishlist': wishlist})

books/templates/books/book_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles1bookdetail.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ book.title }}Book Details</title>

    <style>
        /* CSS for the star rating */
        .stars {
            display: inline-block;
        }

        .star {
            font-size: 20px;
            cursor: pointer;
        }

        .star.checked { 
            color: gold;
        }

        .book-description {
            font-size: 18px; /* Adjust the font size as needed */
            line-height: 1.5; /* Adjust the line height for better readability */
        }

        

    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'books:book_list' %}" class="wormy-link">WormyReads</a>
        <a href="{% url 'books:home' %}" class="home-link">Home</a>
        <a href="{% url 'books:view_wishlist' %}">View Wishlist</a>
    </div>
    

    <div class="book-container">
        <div class="book-details">
            <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="book-cover">
            <div class="book-info">
                <h1 class="book-title">{{ book.title }}</h1>
                <p class="book-label"><strong>Author:</strong> {{ book.author }}</p>
                <p class="book-label"><strong>Book Description:</strong></p>
                <p class="book-description">{{ book.description }}</p>
            </div>
        </div>
        <button id="addToWishlist" class="wishlist-button" data-book-id="{{ book.id }}" onclick="addToWishlist(this)">Add to Wishlist</button>



        <!-- Display existing reviews -->
        <h2>Reviews</h2>
        <ul id="reviews">
            {% for review in book.reviews.all %}
                <li>
                    <div class="stars">
                        {% for i in "12345" %}
                            <span class="star {% if i <= review.rating %}checked{% endif %}" onclick="rateBook({{ review.id }}, {{ i }})">&#9733;</span>
                        {% endfor %}
                    </div>
                    <p>{{ review.comment }}</p>
                </li>
            {% empty %}
                <li>No reviews yet.</li>
            {% endfor %}
        </ul>
    
        <!-- Review Input Box -->
        <h2>Add a Review</h2>
        <div class="stars">
            {% for i in "12345" %}
                <span class="star" onclick="addReview({{ i }})">&#9733;</span>
            {% endfor %}
        </div>
        <textarea id="reviewText" placeholder="Write your review here"></textarea>
        <button id="submitReview" onclick="submitReview()">Submit Review</button>
    </div>
    
    <!-- JavaScript for handling star rating and review submission -->
    <script>


function addToWishlist(buttonElement) {
    const bookId = buttonElement.getAttribute('data-book-id');
    const xhr = new XMLHttpRequest();
    const isAdded = buttonElement.classList.contains('added'); // Check if the book is already added

    xhr.open('POST', isAdded ? '/books/remove_from_wishlist/' : '/books/add_to_wishlist/', true); // Use the appropriate URL for add or remove

    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-CSRFToken', getCookie('csrftoken'));

    xhr.onreadystatechange = function() {
        if (xhr.readyState === 4 && xhr.status === 200) {
            if (isAdded) {
                // If the book was already added, remove it from the wishlist and update the button appearance
                buttonElement.classList.remove('added');
            } else {
                // If the book was not already added, add it to the wishlist and update the button appearance
                buttonElement.classList.add('added');
            }
        } else if (xhr.readyState === 4) {
            console.error('Error updating wishlist. Status:', xhr.status);
        }
    };

    xhr.send('bookId=' + bookId);
}



function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}


        const csrfToken = getCookie('csrftoken');






        function rateBook(reviewId, rating) {
            // Send an AJAX request to update the rating for the review
            // You can implement this functionality in your Django views
            // For now, we'll just update the UI
            const stars = document.querySelectorAll(`[onclick="rateBook(${reviewId}, ${rating})"]`);
            stars.forEach((star, index) => {
                if (index < rating) {
                    star.classList.add('checked');
                } else {
                    star.classList.remove('checked');
                }
            });
        }
        



        function addReview(rating) {
            // Set the selected rating in the review input box
            const reviewText = document.getElementById("reviewText");
            reviewText.value = `Rating: ${rating}/5\n\n`;
        }


    


        function submitReview() {
    // Get the review text from the input box
    const reviewText = document.getElementById("reviewText").value;

    // Extract the rating from the review text
    const ratingMatch = reviewText.match(/Rating: (\d)\/5/);
    let rating = 0;
    if (ratingMatch) {
        rating = parseInt(ratingMatch[1]);
    }

    // Create a new AJAX request
    const xhr = new XMLHttpRequest();
    xhr.open("POST", "/books/submit_review/", true); // Use the actual URL pattern
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.setRequestHeader('X-CSRFToken', getCookie('csrftoken')); // Set CSRF token after initializing xhr

    xhr.onreadystatechange = function () {
        if (xhr.readyState === 4 && xhr.status === 200) {
            // Review submitted successfully
            const response = JSON.parse(xhr.responseText);
            
            // Add the new review to the UI
            const reviewsList = document.getElementById("reviews");
            const newReview = document.createElement("li");
            newReview.innerHTML = `
                <div class="stars">
                    <span class="star checked">&#9733;</span>`.repeat(rating) + `
                    <span class="star">&#9733;</span>`.repeat(5 - rating) + `
                </div>
                <p>${response.comment}</p>`;
            reviewsList.appendChild(newReview);
            
            // Clear the review input box
            document.getElementById("reviewText").value = "";
        }
    };
    
    // Send the review data as JSON
    const data = JSON.stringify({ rating: rating, comment: reviewText });
    xhr.send(data);
}

    </script>

</body>
</html>

books/templates/books/book_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Book Collection</title>
  <!-- Include your stylesheet once in the head -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles1.css' %}">
</head>
<body>


  <div class="black-band">
    <header class="header">
      <a href="{% url 'books:home' %}" class="navbar-link logo">WormyReads</a>
      <a href="{% url 'books:home' %}" class="navbar-link home-link">Home</a>

      
      

      <form action="{% url 'books:search_results' %}" method="GET" class="search-form">
        
        <input type="text" placeholder="Search by name..." name="search_query" class="search-bar">
        <button type="submit" class="search-button">Search</button>
        <a href="{% url 'books:login' %}" class="navbar-link login-link">Login</a>
        <a href="{% url 'books:signup' %}" class="navbar-link signup-link">Signup</a>

      </form>
    </header>
  </div>

  <div class="container">
    {% for book in books %}
      <div class="book-grid-item">
        <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="book-cover">
        <div class="book-info">
          <h2 class="book-title">{{ book.title }}</h2>
          <p class="book-author">{{ book.author }}</p>
        </div>
        <a href="{% url 'books:book_detail' book.id %}" class="more-info-link">More Info</a>
      </div>
    {% endfor %}
  </div>



  <div class="flex">

<div class="flex-container">
    <div class="column">
        <div class="company-info">
            COMPANY
            <br>
            About us
            <br>
            Careers
            <br>
            Terms
            <br>
            Privacy
            <br>
            Interest Based Ads
            <br>
            Ad Preferences
            <br>
            Help
        </div>
    </div>

    <div class="column">
        <div class="work-with-us">
            WORK WITH US
            <br>
            Authors
            <br>
            Advertise
            <br>
            Authors & ads blog
            <br>
            API
        </div>
    </div>

    <div class="column">
        <div class="connect">
            CONNECT
            <br>
            WormyReads on Facebook
            <br>
            WormyReads on Twitter
            <br>
            WormyReads on Instagram
            <br>
            WormyReads on LinkedIn
        </div>
    </div>
</div>

<div class="center">
    © 2024 WormyReads, Inc.
</div>
</body>
</html>

books/templates/books/genre_books.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ genre }} Books</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles3genre.css' %}">
    <style>
        /* Center-align the header */
      
    </style>
</head>
<body>
    <div class="black-band">
        <header class="header">
            <a href="{% url 'books:home' %}" class="navbar-link logo">WormyReads</a>
            <a href="{% url 'books:home' %}" class="navbar-link home-link">Home</a>

            <form action="{% url 'books:search_results' %}" method="GET" class="search-form">
                <input type="text" placeholder="Search by name..." name="search_query" class="search-bar">
                <button type="submit" class="search-button">Search</button>
                <a href="{% url 'books:login' %}" class="navbar-link login-link">Login</a>
                <a href="{% url 'books:signup' %}" class="navbar-link signup-link">Signup</a>
            </form>
        </header>
    </div>
    <nav class="secondary-nav">
        <ul>
            <li><a href="{% url 'books:genre_books' '{{ genre }}' %}">{{ genre }}</a></li>
            

        </ul>
    </nav>

    <div class="container">
        {% csrf_token %}
        {% for book in books %}
        <div class="book-grid-item">
            <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="book-cover">
            <div class="book-info">
                <a href="{% url 'books:book_detail' book.id %}" class="more-info-link">More Info</a>
            </div>
        </div>
        {% empty %}
        <p>No {{ genre|lower }} books found.</p>
        {% endfor %}
    </div>
    

  <div class="flex">

    <div class="flex-container">
        <div class="column">
            <div class="company-info">
                COMPANY
                <br>
                About us
                <br>
                Careers
                <br>
                Terms
                <br>
                Privacy
                <br>
                Interest Based Ads
                <br>
                Ad Preferences
                <br>
                Help
            </div>
        </div>
    
        <div class="column">
            <div class="work-with-us">
                WORK WITH US
                <br>
                Authors
                <br>
                Advertise
                <br>
                Authors & ads blog
                <br>
                API
            </div>
        </div>
    
        <div class="column">
            <div class="connect">
                CONNECT
                <br>
                WormyReads on Facebook
                <br>
                WormyReads on Twitter
                <br>
                WormyReads on Instagram
                <br>
                WormyReads on LinkedIn
            </div>
        </div>
    </div>
    
    <div class="center">
        © 2024 WormyReads, Inc.
    </div>
    </body>
    </html>
    

books/templates/books/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles2home.css' %}">
</head>
<body>
    <div class="white-background">

    <header>
        Wormy<span class="reads">Reads</span>
    </header>

    <!-- Navigation Section -->
    <nav class="secondary-nav">
        <ul>
            <li><a href="{% url 'books:genre_books' 'FICTION' %}">FICTION</a></li>
            <li><a href="{% url 'books:genre_books' 'NON-FICTION' %}">NON-FICTION</a></li>
            <li><a href="{% url 'books:genre_books' 'AUTOBIOGRAPHY' %}">AUTOBIOGRAPHY</a></li>
            <li><a href="{% url 'books:genre_books' 'NON-FICTION' %}">NOVELS</a></li>
            <li><a href="{% url 'books:genre_books' 'THRILLERS' %}">THRILLERS</a></li>
            <li><a href="{% url 'books:genre_books' 'HISTORY' %}">HISTORY</a></li>
            <li><a href="{% url 'books:genre_books' 'POETRY' %}">POETRY</a></li>
            <a href="{% url 'books:view_wishlist' %}">WISHLIST</a>
        </ul>
    </nav>

    <!-- Image Section -->
    <div class="image-container">
        <div class="image-overlay">
            <img src="{% static 'css/images/homeimage.png' %}" alt="Image Description">
            <div class="overlay-text">
                <span class="announcement-text">Announcing the</span><br>
                <span class="best-books">Best Books</span><br>
                <span class="year-text">of 2024</span>
            </div>
        </div>
    </div>

    <!-- Book List Section -->
    <ul class="book-list">
        {% for book in latest_books %}
            <li class="book">
                <a href="{% url 'books:book_list' %}">
                    <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" class="book-cover">
                </a>
            </li>
        {% empty %}
            <li>No books found.</li>
        {% endfor %}
    </ul>
</div>

<div class="black-background"></div>
<div class="image-container">
    <!-- Two images on one line, two below -->
    <div class="image-box">
        <div class="quote-image">
            <img src="{% static 'css/images/quote1.png' %}" alt="Image Description">
            <div class="quote-overlay">
                <span class="quote-text">"So many books, so little time."</span>
                <span class="quote-author">― Frank Zappa</span>
            </div>
        </div>
    </div>
    <div class="image-box">
        <div class="quote-image">
            <img src="{% static 'css/images/quote2.png' %}" alt="Image Description">
            <div class="quote-overlay">
                <span class="quote-text">"A room without books is like a body without a soul."</span>
                <span class="quote-author">― Marcus Tullius Cicero</span>
            </div>
        </div>
    </div>
    <div class="image-box">
        <div class="quote-image">
            <img src="{% static 'css/images/quote3.png' %}" alt="Image Description">
            <div class="quote-overlay">
                <span class="quote-text">"The people who are crazy enough to think they can change the world are the ones who do."</span>
                <span class="quote-author">— Steve Jobs</span>
            </div>
        </div>
    </div>
    <div class="image-box">
        <div class="quote-image">
            <img src="{% static 'css/images/quote4.png' %}" alt="Image Description">
            <div class="quote-overlay">
                <span class="quote-text">"Show me a family of readers, and I will show you the people who move the world."</span>
                <span class="quote-author">– Napoleon Bonaparte</span>
            </div>
        </div>
    </div>
</div>

<!-- Add this script before the closing </body> tag -->
<script>
    const imageBoxes = document.querySelectorAll(".image-box");

    const observerOptions = {
        root: null,
        rootMargin: "0px",
        threshold: 0.2, // Adjust the threshold as needed
    };

    const observer = new IntersectionObserver((entries, observer) => {
        entries.forEach((entry) => {
            if (entry.isIntersecting) {
                entry.target.classList.add("animate-fade-in");
                observer.unobserve(entry.target);
            }
        });
    }, observerOptions);

    imageBoxes.forEach((imageBox) => {
        observer.observe(imageBox);
    });
</script>

<!-- ... your existing HTML ... -->
<!-- ... your existing HTML ... --><!-- ... your existing HTML ... -->
<!-- ... your existing HTML ... -->

<div class="white-thin-line"></div>

<div class="flex-container">
    <div class="column">
        <div class="company-info">
            COMPANY
            <br>
            About us
            <br>
            Careers
            <br>
            Terms
            <br>
            Privacy
            <br>
            Interest Based Ads
            <br>
            Ad Preferences
            <br>
            Help
        </div>
    </div>

    <div class="column">
        <div class="work-with-us">
            WORK WITH US
            <br>
            Authors
            <br>
            Advertise
            <br>
            Authors & ads blog
            <br>
            API
        </div>
    </div>

    <div class="column">
        <div class="connect">
            CONNECT
            <br>
            WormyReads on Facebook
            <br>
            WormyReads on Twitter
            <br>
            WormyReads on Instagram
            <br>
            WormyReads on LinkedIn
        </div>
    </div>
</div>

<div class="center">
    © 2024 WormyReads, Inc.
</div>

<!-- ... rest of your HTML ... -->

<!-- ... rest of your HTML ... -->

</body>
</html>

books/templates/books/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="login-container">
  

  <h2>Login</h2>
  <form method="post" action="{% url 'books:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

books/templates/books/password_reset.html
{% extends 'base.html' %}

{% block content %}
<div class="password-reset-container">
    <h2>Password Reset</h2>
    <form method="post" action="{% url 'books:password_reset' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

books/templates/books/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="password-reset-confirm-container">
    <h2>Confirm Password Reset</h2>
    <form method="post" action="{% url 'books:password_reset_confirm' uidb64=uidb64 token=token %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirm Password Reset</button>
    </form>
</div>
{% endblock %}